#!/usr/bin/env python3

import sys
import os
if len(sys.argv) < 2:
    print("Usage: db_reset/ celery")
    sys.exit(0)

if sys.argv[1] == 'db_reset':
    import os
    try:
        os.remove("app/aafood.db")
    except Exception as e:
        pass
    from app.models import db
    db.create_all()
    print("Reset Database Done!")

# 執行 Celery Instance
if sys.argv[1] == 'celery':
    os.system("celery -A app.celery worker")
