
TMT_FIX_TRANSLATION = 'TMT_FIX_TRANSLATION'
TMT_CONFIRM_TRANSLATION = 'TMT_CONFIRM_TRANSLATION'
TMT_CANCEL = 'TMT_CANCEL'
TMT_MORE = 'TMT_MORE'
TMT_PICTURE = 'TMT_PICTURE'
TMT_RECIPE = 'TMT_RECIPE'
TMT_WHERE_TO_BUY = 'TMT_WHERE_TO_BUY'

STATE_WAIT_FOR_FIX_CHINESE = 'wait_for_fix_chinese'
STATE_WAIT_FOR_FIX_ENGLISH = 'wait_for_fix_english'
STATE_En2ZhTw_IS_CALLED = 'en_to_zhtw_is_called'
STATE_ZhTw2En_IS_CALLED = 'zhtw_to_en_is_called'


#MSG_HANDLER_COMPLETE = 'OK'
#MSG_HANDLER_REJECT = 'rejected'
