
PAYLOAD_CONFIRM = 'PAYLOAD_CONFIRM'
PAYLOAD_FIX = 'PAYLOAD_FIX'
PAYLOAD_CANCEL = 'PAYLOAD_CANCEL'
PAYLOAD_MORE = 'PAYLOAD_MORE'
PAYLOAD_PICTURE = 'PAYLOAD_PICTURE'
PAYLOAD_RECIPE = 'PAYLOAD_RECIPE'
PAYLOAD_WHERE_TO_BUY = 'PAYLOAD_WHERE_TO_BUY'

